import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BadgePercent,
  Ban,
  Bell,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Eye,
  Filter,
  Grid2X2,
  GridIcon,
  Headphones,
  HelpCircle,
  Home,
  Inbox,
  Info,
  Keyboard,
  KeyRound,
  LayoutDashboard,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  type LucideProps,
  Map as MapIcon,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Monitor,
  Navigation,
  Package,
  PackageCheck,
  Pause,
  Pencil,
  Percent,
  Phone,
  PhoneCall,
  Plus,
  PlusCircle,
  Route,
  Save,
  ScrollText,
  Search,
  Send,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sprout,
  Tag,
  Timer,
  Trash2,
  TrendingUp,
  Truck,
  Unlock,
  User,
  UserPlus,
  Users,
  Wallet,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

/**
 * Wrapper sur lucide-react avec typage strict des noms d'icônes utilisés
 * dans MATA. Centraliser ici permet :
 *  - Tree-shaking : seules les icônes référencées sont bundlées
 *  - Garantie qu'un nom d'icône invalide est détecté à la compilation
 *  - Substitution facile si on change de lib plus tard
 *
 * Référence : ARCHITECTURE.md §8 « Icônes : lucide-react, wrapper <Icon> ».
 */

const ICONS = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  'badge-percent': BadgePercent,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  eye: Eye,
  filter: Filter,
  grid: GridIcon,
  'grid-2x2': Grid2X2,
  headphones: Headphones,
  'help-circle': HelpCircle,
  home: Home,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  keyboard: Keyboard,
  'layout-dashboard': LayoutDashboard,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  map: MapIcon,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  monitor: Monitor,
  navigation: Navigation,
  package: Package,
  'package-check': PackageCheck,
  pause: Pause,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  'phone-call': PhoneCall,
  plus: Plus,
  'plus-circle': PlusCircle,
  route: Route,
  save: Save,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sprout: Sprout,
  tag: Tag,
  timer: Timer,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  truck: Truck,
  unlock: Unlock,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = Omit<LucideProps, 'ref'> & {
  name: IconName;
};

export function Icon({ name, ...props }: IconProps): React.JSX.Element {
  const Component = ICONS[name];
  return <Component {...props} />;
}
